{{ if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cm
data:
  {{- range $key, $value := .Values.configMap.data }}
  {{- $key }}: {{ $value }}
  {{- end }}
{{ end }}