apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      containers:
      - name: {{ .Values.deployment.containerName }}
        image: {{ .Values.deployment.image.repository }}
        imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
        command: {{ .Values.deployment.image.command }}
        envFrom:
        - secretRef:
            name: {{ .Values.deployment.secret.name }}
        - configMapRef:
            name: {{ .Values.deployment.configMap.name }}
        ports:
        - containerPort: 80
        volumeMounts:
        - name: {{ .Values.deployment.persistentVolumeClaim.name }}
          mountPath: {{ .Values.deployment.persistentVolumeClaim.mountPath }}
      volumes:
      - name: {{ .Values.deployment.persistentVolumeClaim.name }}
        persistentVolumeClaim:
          claimName: {{ .Values.deployment.persistentVolumeClaim.name }}