apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-deployment
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-deployment
    spec:
      serviceAccountName: default
      containers:
        - name: {{ .Values.containers.name }}
          image: {{ .Values.containers.image }}
          imagePullPolicy: {{ .Values.containers.pullPolicy }}
          command:
          {{- toYaml .Values.containers.command | nindent 10 }}
          env:
            {{- range .Values.containers.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          resources:
          requests:
            cpu: {{ .Values.containers.resources.requests.cpu }}
            memory: {{ .Values.containers.resources.requests.memory }}
          limits:
            cpu: {{ .Values.containers.resources.limits.cpu }}
            memory: {{ .Values.containers.resources.limits.memory }}
          volumeMounts:
            {{- range .Values.containers.volumeMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              {{- end }}
          volumes:
            {{- range .Values.volumes }}
          - name: {{ .name }}
            {{- if .configMap }}
            configMap:
              name: {{ .configMap.name }}
            {{- end }}
            {{- if .secret }}
            secret:
              secretName: {{ .secret.name }}
            {{- end }}
          {{- end }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistentVolumeClaim.claimName }}