apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-deployment
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-deployment
    spec:
      serviceAccountName: default
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.container.image }}
          imagePullPolicy: {{ .Values.container.pullPolicy }}
          command:
          {{- toYaml .Values.container.command | nindent 10 }}
          env:
            {{- range .Values.container.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
        resources:
          requests:
            cpu: {{ .Values.container.resources.requests.cpu }}
            memory: {{ .Values.container.resources.requests.memory }}
          limits:
            cpu: {{ .Values.container.resources.limits.cpu }}
            memory: {{ .Values.container.resources.limits.memory }}
        volumeMounts:
          {{- range .Values.container.volumeMounts }}
          - name: {{ .name }}
            mountPath: {{ .mountPath }}
          {{- end }}
      volumes:
        {{- range .Values.volumes }}
        - name: {{ .name }}
          {{- if .configMap }}
          configMap:
            name: {{ .configMap.name }}
          {{- end }}
          {{- if .secret }}
          secret:
            secretName: {{ .secret.name }}
          {{- end }}
        {{- end }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistentVolumeClaim.claimName }}