apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv
spec:
  capacity:
    storage: {{ .Values.persistentVolume.capacity }}
  accessModes:
    {{- toYaml .Values.persistentVolume.accessModes | nindent 4 }}
  hostPath:
    path: {{ .Values.persistentVolume.hostPath }}