apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.pv.name }}
spec:
  storageClassName: {{ .Values.pv.storageClassName }}
  capacity:
    storage: {{ .Values.pv.capacity }}
  accessModes:
    {{- toYaml .Values.pv.accessModes | nindent 4 }}
  hostPath:
    path: {{ .Values.pv.hostPath }}