apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv
  labels:
    type: local
spec:
  storageClassName: {{ .Values.persistentVolume.storageClassName }}
  capacity:
    storage: {{ .Values.persistentVolume.capacity }}
  accessModes:
    {{- toYaml .Values.persistentVolume.accessModes | nindent 4 }}
  hostPath:
    path: {{ .Values.persistentVolume.hostPath }}