apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-storage-pvc
spec:
  accessModes:
    - ReadWriteOnce  #  Requerido
  resources:
    requests:
      storage: 50Mi  #  Requerido: Tamaño del almacenamiento solicitado
  volumeName: image-storage-pv
  storageClassName: local # Requerido: para que coincida con nuestro PV
