apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: python-app-role
  namespace: default
rules:
- apiGroups: [""] # Requerido - "" -> Apis de recursos básicos como Pods, Services, ConfigMaps, Secrets, Namespaces, etc.
  resources: ["pods", "services"]  # Requerido (Similar a servicios de AWS como EC2, S3, RDS, etc.)
  verbs: ["get", "list", "watch"]  #  Requerido, permisos asignados (Similar a las IAM Actions, como ec2:DescribeInstances, s3:ListBucket, etc.)

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: python-app-sa
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: python-app-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: python-app-sa
  namespace: default
roleRef:
  kind: Role
  name: python-app-role
  apiGroup: rbac.authorization.k8s.io


