configMap:
  enabled: false
  name: nginx-config
  data:
    wp.conf: |
      server {
          listen       80;
          server_name  _;

          location / {
              root   /var/www/html;
              index  index.php index.html index.htm;
          }
      }
replicaCount: 1
containers:
  name: nginx
  image: nginx:1.15.8
  imagePullPolicy: IfNotPresent
  command: ["nginx", "-g", "daemon off;"]
  env:
    - name: wp-name
      value: local
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  volumeMounts:
    - name: nginx-config
      mountPath: /etc/nginx/conf.d
volumes:
  - name: nginx-config
    configMap:
      name: nginx-config
persistentVolumeClaim:
  claimName: "persistent-storage"
hpa:
  enabled: false
ingress:
  host: wordpress.local
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
persistentVolume:
  storageClassName: local
  capacity: 1Gi
  accessModes: ReadWriteOnce
  hostPath: /home/ec2-user/wordpress
persistentVolumeClaim:
  storageClassName: local
  accessModes: ReadWriteOnce
  storage: 1Gi
secret:
  data:
    DB_PASSWORD: wordpress
service:
  name: http
  port: 80
  type: ClusterIP
test:
  enabled: false