configMap:
  name: nginx-config
  data:
    wp.conf: |
      server {
          listen       80;
          server_name  _;

          location / {
              root   /var/www/html;
              index  index.php index.html index.htm;
          }
      }
deployment:
  replicaCount: 1
  template:
    containers:
      name: nginx
      image: nginx:1.15.8
      imagePullPolicy: IfNotPresent
      command: ["nginx", "-g", "daemon off;"]
      env:
        - name: wp-name
          value: local
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
      volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
    volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
    persistentVolumeClaim:
      claimName: "persistent-storage"
hpa:
  enabled: false
ingress:
  host: wordpress.local
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
persistentVolume:
  storageClassName: local-storage
  capacity: 1Gi
  accessModes: ReadWriteOnce
  hostPath: /var/www/html
persistentVolumeClaim:
  storageClassName: local-storage
  accessModes: ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
secret:
  data:
    - DB_NAME: wordpress
    - DB_USER: wordpress
    - DB_PASSWORD: wordpress
    - DB_HOST: mysql
    - DB_PORT: 3306
    - WP_NAME: local
service:
  portName: "http"
  port: 80
  type: ClusterIP
test:
  enabled: false