#Deployment
deployment:
  name: wordpress
  replicaCount: 1
  containerName: wordpress
  image:
    repository: gusalvarado/k8s-ningx:latest
    imagePullSecrets:
      - name: imagepull-secret
    pullPolicy: IfNotPresent
  secret:
    name: wordpress-secret
  configMap:
    name: wordpress-config
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi
  persistentVolumeClaim:
    name: wordpress-pvc
    mountPath: /var/www/html
#Service
service:
  name: wordpress
  portName: http
  port: 80
  targetPort: 80
  type: LoadBalancer
#Ingress
ingress:
  host: wordpress.local
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "/"
#Secret
secret:
  name: wordpress-secret
  data:
    DB_NAME: d29yZHByZXNz
    DB_USER: d29yZHByZXNz
    DB_PASSWORD: d29yZHByZXNz
imagepullsecret:
  name: imagepull-secret
  data:
    .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICJodWIuZG9ja2VyLmNvbSI6IHsKICAgICAgICAgICAgInVzZXJuYW1lIjogImd1c2FsdmFyYWRvIiwKICAgICAgICAgICAgInBhc3N3b3JkIjogInp4S0FOT05AMTIzNCIsCiAgICAgICAgICAgICJlbWFpbCI6ICJnYWx2YXJhZG9jcnVlQGdtYWlsLmNvbSIKICAgICAgICB9CiAgICB9Cn0=
#ConfigMap
cm:
  name: wordpress-config
  data:
    info.php: |
      <?php
      phpinfo();
#PersistentVolume
persistentVolume:
  name: wordpress-pv
  accessModes:
    - ReadWriteMany
  capacity: 1Gi
  storageClass: gp2
  hostPath: /mnt/data
#PersistentVolumeClaim
persistentVolumeClaim:
  name: wordpress-pvc
  storage: 500Mi